#!/usr/bin/env python3
'''
A simple manager for book reading and note.
'''

from __future__ import print_function, absolute_import
from argparse import ArgumentParser
from readmanager import main

# ===================================================================
# Parser
description = __doc__
parser = ArgumentParser(description=description)
mode = parser.add_mutually_exclusive_group()
mode.add_argument("-c", dest='check', action="store_true", \
        help="Check-mode: check book items")
mode.add_argument("-r", dest='read', action="store_true", \
        help="Read-mode: read books without access to modify book items")
mode.add_argument("-b", dest='batch', nargs="+", \
        help="Batch-mode (for utility test only))")
params = parser.parse_args()
# ===================================================================

if not params.batch:
    ui = main.readmanager_ui(modeCheck=params.check, modeRead=params.read)
else:
    main.readmanager_batch(params.batch)

